name: Python CI/CD Pipeline # workflow name

# trigger the execution when changes pushes to master
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# define where to execute , default is ubuntu, you may change to windows
jobs:
  # define the jobs e.g. build , clean, deploy etc.
  build:
    runs-on: ubuntu-latest

    # define steps
    # 1. checkout
    # 2. setup python
    # 3. install dependencies
    # run the tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'   # Change if your project uses a different Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Optional) If you have tests using pytest, keep this. Otherwise, you can comment/remove it.
      - name: Run tests
        run: |
          pytest tests/
